POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

###
POST http://localhost:8000/api/register HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123",
    "gender": "F",
    "dob": "1999-03-05",

    "name": {
        "first_name": "Lila",
        "middle_name": "",
        "last_name": "Bonnet"
    },

    "address": {
        "address_line1": "Paris, France",
        "address_line2": "",
        "city": "Paris",
        "state": "Seine-et-Marne",
        "country": "France"
    },

    "contact": {
        "phone_number": "04-24-68-75-09",
        "status": "A"
    }
}

###
POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

###
POST http://localhost:8000/api/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI3Nzk1LCJpYXQiOjE3Mzc3MjQxOTUsImp0aSI6ImYzM2NiNDdiM2I0OTRjMjk4MWZkNzM4ZWM0YWI3OWM4IiwidXNlcl9pZCI6ImQyYTMxOWUwYTliNDQ0ODFhZWRkYWY2ODY3ZWVmYzNjIn0.VPQ6Y9ZOfFGweopxiftrmv2yAluspyg3_5nGqFbpzFw

###
POST http://127.0.0.1:8000/api/profile/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI4NDM2LCJpYXQiOjE3Mzc3MjQ4MzYsImp0aSI6IjBjMWI5NTE4Nzc4MTRmYWZiYzNhYzg0YzgyZmQ5ZWU2IiwidXNlcl9pZCI6ImI5ZjVmNWZhOTMyOTQwOTBhNmMzNGQ1MjI2NWUzN2ZiIn0.Uqr2dyyyCyc9GxtwZSqoaSplkPP0s3GS7A1POMPo3mc
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="IMG_4899 copy.jpg"
Content-Type: image/jpeg

< D:/__all__/IMG_4899 copy.jpg
--boundary123--

###
GET http://127.0.0.1:8000/api/profile/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI4NDM2LCJpYXQiOjE3Mzc3MjQ4MzYsImp0aSI6IjBjMWI5NTE4Nzc4MTRmYWZiYzNhYzg0YzgyZmQ5ZWU2IiwidXNlcl9pZCI6ImI5ZjVmNWZhOTMyOTQwOTBhNmMzNGQ1MjI2NWUzN2ZiIn0.Uqr2dyyyCyc9GxtwZSqoaSplkPP0s3GS7A1POMPo3mc

###
GET http://localhost:8000/api/user/documents HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI4NDM2LCJpYXQiOjE3Mzc3MjQ4MzYsImp0aSI6IjBjMWI5NTE4Nzc4MTRmYWZiYzNhYzg0YzgyZmQ5ZWU2IiwidXNlcl9pZCI6ImI5ZjVmNWZhOTMyOTQwOTBhNmMzNGQ1MjI2NWUzN2ZiIn0.Uqr2dyyyCyc9GxtwZSqoaSplkPP0s3GS7A1POMPo3mc

###
POST http://127.0.0.1:8000/api/user/documents HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MjkzNzk3LCJpYXQiOjE3MzcyOTAxOTcsImp0aSI6IjYyNDRiNjdiYTY2NTQ5OGFiOWJiNzVjNGU3YTZmNzBhIiwidXNlcl9pZCI6ImRmZDY2ZGZiLTE3NDItNDdmZi04ZTk5LTdhZThjNWIxNjhiNyJ9.Sok8xandfZiK15cbcih8LOAJBaTFXscrYWPu8rWJ8lE
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="title"

Certificate
--boundary123
Content-Disposition: form-data; name="file"; filename="document.jpg"
Content-Type: image/jpeg

< D:\__all__\pdf\1st Sem - Board.jpg
--boundary123--

###
GET http://localhost:8000/api/recruiter HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NjQ5MDY2LCJpYXQiOjE3Mzc2NDU0NjYsImp0aSI6ImM4ZWVjYWU3NDhhNDQxNGZhZDM3YWY0NTJmYjkxNTYxIiwidXNlcl9pZCI6Ijg4MGNlNDIwLTQwMGItNGUzNC04NGJmLTQ1ZTlmZGQ1NDMzYiJ9.gZQIkNY1oE0PKErIgd-NTOIyhlEjltOqk2V4mfDKGcg

###
POST http://localhost:8000/api/recruiter HTTP/1.1
Content-Type: application/json

{
    "email": "hrtest@test.com",
    "password": "hrtest123",
    "gender": "F",
    "dob": "1999-03-05",

    "name": {
        "first_name": "Lila",
        "middle_name": "",
        "last_name": "Bonnet"
    },

    "address": {
        "address_line1": "Paris, France",
        "address_line2": "",
        "city": "Paris",
        "state": "Seine-et-Marne",
        "country": "France"
    },

    "contact": {
        "phone_number": "04-24-68-75-09",
        "status": "A"
    },

    "company_name": "Google",
    "designation": "HR",
    "is_staff": "true"
}


###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "hrtest@test.com",
    "password": "hrtest123"
}

###
POST http://localhost:8000/api/job HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzIwNTIzLCJpYXQiOjE3Mzc3MTY5MjMsImp0aSI6ImJjN2QzOTk4ODZkZjRkODQ4MzZhNTMzYWQ4MThiZTI3IiwidXNlcl9pZCI6Ijg4MGNlNDIwLTQwMGItNGUzNC04NGJmLTQ1ZTlmZGQ1NDMzYiJ9.GVls_tc5-p8On2M35nM-67fhbK0G-9ijRQZjqKh_jTM

{
    "title": "Software Engineer",
    "description": "Responsible for designing, developing, and maintaining software applications.",
    "requirements": "Bachelor's degree in Computer Science or related field, 2+ years of experience in software development.",
    "salary": "60,000 - 80,000 USD per year",
    "location": "New York, NY",
    "deadline": "2025-02-15"
}

###
GET http://localhost:8000/api/job HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NjQ1MzQ1LCJpYXQiOjE3Mzc2NDE3NDUsImp0aSI6IjAzYzNjOTkxNTVkNzQ3ZGE4M2RlYzNhOWFiNDIwYTg2IiwidXNlcl9pZCI6Ijg4MGNlNDIwLTQwMGItNGUzNC04NGJmLTQ1ZTlmZGQ1NDMzYiJ9.oPGQp-ckTsX82cepgZNoAyJ19TnG_fvdf0l-tF_sgRw

###
DELETE http://localhost:8000/api/job HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NjQ1MzQ1LCJpYXQiOjE3Mzc2NDE3NDUsImp0aSI6IjAzYzNjOTkxNTVkNzQ3ZGE4M2RlYzNhOWFiNDIwYTg2IiwidXNlcl9pZCI6Ijg4MGNlNDIwLTQwMGItNGUzNC04NGJmLTQ1ZTlmZGQ1NDMzYiJ9.oPGQp-ckTsX82cepgZNoAyJ19TnG_fvdf0l-tF_sgRw
Content-Type: application/json

{
    "job_id": "8f45fb89-7d59-48ba-afc0-0535a6b7d136"
}
