@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTYwOTY5LCJpYXQiOjE3MzgxNTczNjksImp0aSI6ImMzNzVkMjU0MjczYTRkOTlhNjc3ODg1YzJhNDQ2MjlkIiwidXNlcl9pZCI6ImFmYTg3ODY5ODY2YjRmYmE4NTY1OTFhOTQxODhjYTA2In0.Qgw_k6qa9VRH0-7myrzojMf6W3cc0BFg9CKF1QIkbTA

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

###
POST http://localhost:8000/api/register HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123",
    "gender": "F",
    "dob": "1999-03-05",

    "name": {
        "first_name": "Lila",
        "middle_name": "",
        "last_name": "Bonnet"
    },

    "address": {
        "address_line1": "Paris, France",
        "address_line2": "",
        "city": "Paris",
        "state": "Seine-et-Marne",
        "country": "France"
    },

    "contact": {
        "phone_number": "04-24-68-75-09",
        "status": "A"
    }
}

###
POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

###
POST http://localhost:8000/api/logout HTTP/1.1
Authorization: Bearer {{token}}

###
POST http://127.0.0.1:8000/api/profile/image HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="IMG_4899 copy.jpg"
Content-Type: image/jpeg

< D:/__all__/IMG_4899 copy.jpg
--boundary123--

###
GET http://127.0.0.1:8000/api/profile/image HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://localhost:8000/api/user/documents HTTP/1.1
Authorization:  Bearer {{token}}

###
POST http://127.0.0.1:8000/api/user/documents HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="title"

Certificate
--boundary123
Content-Disposition: form-data; name="file"; filename="document.jpg"
Content-Type: image/jpeg

< D:\__all__\pdf\1st Sem - Board.jpg
--boundary123--

###
GET http://localhost:8000/api/recruiter HTTP/1.1
Authorization: Bearer {{token}}

###
POST http://localhost:8000/api/recruiter HTTP/1.1
Content-Type: application/json

{
    "email": "hrtest@test.com",
    "password": "hrtest123",
    "gender": "F",
    "dob": "1999-03-05",

    "name": {
        "first_name": "Lila",
        "middle_name": "",
        "last_name": "Bonnet"
    },

    "address": {
        "address_line1": "Paris, France",
        "address_line2": "",
        "city": "Paris",
        "state": "Seine-et-Marne",
        "country": "France"
    },

    "contact": {
        "phone_number": "04-24-68-75-09",
        "status": "A"
    },

    "company_name": "Google",
    "designation": "HR",
    "is_staff": "true"
}


###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "hrtest@test.com",
    "password": "hrtest123"
}

###
POST http://localhost:8000/api/job HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Software Engineer",
    "description": "Responsible for designing, developing, and maintaining software applications.",
    "requirements": "Bachelor's degree in Computer Science or related field, 2+ years of experience in software development.",
    "salary": "60,000 - 80,000 USD per year",
    "location": "New York, NY",
    "deadline": "2025-02-15"
}

###
GET http://localhost:8000/api/job HTTP/1.1
Authorization: Bearer {{token}}

###
DELETE http://localhost:8000/api/job HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "job_id": "8f45fb89-7d59-48ba-afc0-0535a6b7d136"
}
