# Generated by Django 5.1.2 on 2025-01-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profiles',
            new_name='User_Profile_Images',
        ),
    ]
