# Generated by Django 5.1.2 on 2025-01-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_profiles_user_profile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile_images',
            old_name='file',
            new_name='image',
        ),
    ]
