# Generated by Django 5.1.2 on 2025-01-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_file_user_profile_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_images',
            name='title',
        ),
    ]
