# Generated by Django 5.1.2 on 2025-01-24 11:20

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recruiter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_applications',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_contact',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_documents',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_name',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_profile_images',
            name='id',
            field=models.CharField(default=api.utils.generate_random_ids, editable=False, primary_key=True, serialize=False),
        ),
    ]
